esphome:
  name: esp32p4

esp32:
  variant: esp32p4
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

# Используем только UART-логгер, он надежнее
logger:
  level: DEBUG

# Включаем Wi-Fi
wifi:
  ssid: "MTS_GPON_ab2b70"
  password: "Gbi393a3"

# Включаем web-сервер
web_server:
  port: 80

# Мигаем подсветкой, чтобы подать знак
output:
  - platform: ledc
    pin: GPIO23
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Backlight
    restore_mode: ALWAYS_ON
