esphome:
  name: esp32p4
  on_boot:
    priority: 500
    then:
      - script.execute: blink_ip

esp32:
  variant: esp32p4
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

logger:
  level: DEBUG

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

wifi:
  ssid: "MTS_GPON_ab2b70"
  password: "Gbi393a3"

output:
  - platform: ledc
    pin: GPIO23
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Backlight
    id: backlight

script:
  - id: blink_digit
    parameters:
      digit: int
    then:
      - if:
          condition:
            lambda: 'return digit == 0;'
          then:
            - light.turn_on:
                id: backlight
                brightness: 100%
            - delay: 1.5s
            - light.turn_off: backlight
            - delay: 0.5s
      - else:
          - repeat:
              count: !lambda 'return digit;'
              then:
                - light.turn_on:
                    id: backlight
                    brightness: 100%
                - delay: 0.5s
                - light.turn_off: backlight
                - delay: 0.3s
          - delay: 0.5s

  - id: blink_ip
    then:
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: backlight
          brightness: 100%
      - delay: 3s
      - light.turn_off: backlight
      - delay: 1s
      - lambda: |-
          std::string ip = id(wifi_ap).get_ip_address().str();
          for (char c : ip) {
            if (c >= '0' && c <= '9') {
              id(blink_digit).execute(c - '0');
            } else {
              delay(500);
            }
          }
      - light.turn_on:
          id: backlight
          brightness: 100%
